baseURL: "https://hacksocnotts.co.uk/"
title: HackSoc
paginate: 10
theme: soctor-who-theme

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: true
buildExpired: false

minify:
    disableXML: true
    # minifyOutput: true

outputs:
    home:
        - HTML
        - RSS
        - JSON
    section:
        - Calendar
        - HTML
        - JSON
    page:
        - HTML
        - JSON
        
params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    description: "HackSoc Nottingham"
    author: HackSoc Committee
    #images: ["./images/logo.png"]
    #assets:
    #    favicon: "/icon.svg"


    fuseOpts:
        isCaseSensitive: false
        shouldSort: false
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]

    logoPath: /img/logo.svg
    joinURL: https://www.su.nottingham.ac.uk/societies/society/hack/

menu:
    main:
        - identifier: hacknotts
          name: HackNotts
          url: https://hacknotts.com/
          weight: 10
        - identifier: hackquarantine
          name: Hack Quarantine
          url: https://hackquarantine.com/
          weight: 11
    footer:
        - identifier: code-of-conduct
          name: Code of Conduct
          url: /code-of-conduct
        - identifier: twitter
          name: Twitter
          url: https://twitter.com/SoctorWho
        - identifier: constitution
          name: Constitution
          url: /u/constitution.pdf

taxonomies:
    category: categories
    tag: tags
    series: series

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true
